import { copyFileSync, existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import YAML from 'yaml';
import { loadGlobalConfig } from '../lib/config';
import { readFile, writeFile } from '../lib/fs';
import { getProjectClaudePath, getProjectConfigPath } from '../lib/paths';
import { GLOBAL_DIR } from '../lib/paths';
import type { Block, BlockReference, LocalConfig } from '../types';
import { loadAgent } from './agent';
import { loadBlock } from './block';
import { loadCommand } from './command';
import { loadProfile } from './profile';

export interface GenerateOptions {
  includeGlobal?: boolean;
  projectPath?: string;
}

export function generateClaudeMd(
  profileSlug: string,
  options: GenerateOptions = {}
): { content: string; blocks: BlockReference[] } {
  const profile = loadProfile(profileSlug);
  const globalConfig = loadGlobalConfig();
  const includeGlobal = options.includeGlobal ?? globalConfig?.global?.enabled ?? true;

  const blocks: Block[] = [];
  const blockRefs: BlockReference[] = [];

  // Load all blocks from profile
  for (const blockSlug of profile.config.blocks) {
    const block = loadBlock(blockSlug);
    blocks.push(block);
    blockRefs.push({
      name: blockSlug,
      version: block.frontmatter.version,
      hash: block.hash,
    });
  }

  // Build header
  const blockList = blockRefs.map((b) => `${b.name}@${b.version}`).join(', ');
  const header = `<!-- Generated by ContextMark - Profile: ${profileSlug} -->
<!-- Do not edit manually. Use \`contextmark update\` to refresh. -->
<!-- Blocks: ${blockList} -->

`;

  // Build content
  let content = header;
  content += '# Project Context\n\n';

  // Add global context if enabled
  if (includeGlobal) {
    const globalClaudePath = join(GLOBAL_DIR, 'CLAUDE.md');
    if (existsSync(globalClaudePath)) {
      const globalContent = readFile(globalClaudePath);
      content += `${globalContent.trim()}\n\n---\n\n`;
    }
  }

  // Add each block's content
  for (const block of blocks) {
    content += `${block.content}\n\n---\n\n`;
  }

  // Remove trailing separator
  content = content.replace(/\n\n---\n\n$/, '\n');

  return { content, blocks: blockRefs };
}

export function writeClaudeMd(
  projectPath: string,
  profileSlug: string,
  options: GenerateOptions = {}
): LocalConfig {
  const profile = loadProfile(profileSlug);
  const { content, blocks } = generateClaudeMd(profileSlug, options);

  // Write CLAUDE.md
  const claudePath = getProjectClaudePath(projectPath);
  writeFile(claudePath, content);

  // Copy agents from profile
  const agents: string[] = [];
  if (profile.config.agents && profile.config.agents.length > 0) {
    const skillsDir = join(projectPath, '.claude', 'skills');
    mkdirSync(skillsDir, { recursive: true });

    for (const agentSlug of profile.config.agents) {
      try {
        const agent = loadAgent(agentSlug);
        const destPath = join(skillsDir, `${agentSlug}.md`);
        copyFileSync(agent.path, destPath);
        agents.push(agentSlug);
      } catch {
        // Agent not found, skip
      }
    }
  }

  // Copy commands from profile
  const commands: string[] = [];
  if (profile.config.commands && profile.config.commands.length > 0) {
    const commandsDir = join(projectPath, '.claude', 'commands');
    mkdirSync(commandsDir, { recursive: true });

    for (const commandSlug of profile.config.commands) {
      try {
        const cmd = loadCommand(commandSlug);
        const destPath = join(commandsDir, `${commandSlug}.md`);
        copyFileSync(cmd.path, destPath);
        commands.push(commandSlug);
      } catch {
        // Command not found, skip
      }
    }
  }

  // Create local config
  const localConfig: LocalConfig = {
    profile: profileSlug,
    blocks,
    agents,
    commands,
    generated_at: new Date().toISOString(),
  };

  // Write .contextmark.yml
  const configPath = getProjectConfigPath(projectPath);
  writeFile(
    configPath,
    `# Auto-generated by ContextMark - do not edit manually\n${YAML.stringify(localConfig)}`
  );

  return localConfig;
}

export function previewClaudeMd(profileSlug: string, options: GenerateOptions = {}): string {
  const { content } = generateClaudeMd(profileSlug, options);
  return content;
}
